variables:
  majorVersion: '1'
  minorVersion: '0'
  buildConfiguration: 'Release'
  projectName: 'ThomasMathers.Infrastructure.IAM.Emails'
  testProjectName: 'ThomasMathers.Infrastructure.IAM.Emails.Tests'

name: '$(majorVersion).$(minorVersion).$(Rev:r)'

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - $(projectName)
      - $(testProjectName)

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: '$(projectName)/$(projectName).csproj'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration)'
    projects: '$(testProjectName)/$(testProjectName).csproj'
- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: 'pack'
    packagesToPack: '$(projectName)/$(projectName).csproj'
    versioningScheme: 'byBuildNumber'
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
